sudo: false

language: node_js
node_js:
  - "stable"
install:
  - npm install mocha chai --save-dev
  - npm run test
cache:
  directories:
  - node_modules
script: echo "mocha"
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      
