sudo: false

language: node_js
node_js:
  - "stable"
install:
  - npm install mocha chai --save-dev
  - npm install --save-dev coveralls mocha-lcov-reporter
after_success:
  - npm run coveralls
jobs:
  include:
    - script: mocha --coverage && cat ./coverage/lcov.info | coveralls
